AWSTemplateFormatVersion: 2010-09-09
Description: "Sample ES Cluster"
Parameters:
  ElasticSearchName:
    Type: String
    Default: moj-es
  IPAddress:
    Type: String
    Default: 77.108.144.130
Resources:
  ElasticSearchDemo:
    Type: AWS::Elasticsearch::Domain
    Properties:
      AccessPolicies:
        Statement:
          - Effect: Allow
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: !Sub arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${ElasticSearchName}/*
            Condition:
              IpAddress:
                aws:SourceIp:
                  - !Ref IPAddress
      DomainName: !Ref ElasticSearchName
      ElasticsearchVersion: '7.1'
      ElasticsearchClusterConfig:
        InstanceType: t2.small.elasticsearch
        InstanceCount: 4
        ZoneAwarenessEnabled: true
      EBSOptions:
        EBSEnabled: true
        VolumeType: gp2
        VolumeSize: 20
